### ISSUE TITLE
it doesnt work?

### ISSUE THREAD

**Issue by dxcvvxd** [Saltssaumure/ClassUpdate#2]
im using comfy theme with a few modifications (like 2 lines of code) and when i paste the theme, it doesnt change anything in the code, i used `diff` to check
what should i do?

**Comment by Saltssaumure** [comment]
Please provide a screenshot of how you're using the tool

**Comment by dxcvvxd** [comment]
here you go
![image](https://github.com/Saltssaumure/ClassUpdate/assets/77129815/0d9562b9-c905-4d1d-93a8-ed42a011460e)

**Comment by Saltssaumure** [comment]
This isn't my tool.
